# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/jpinyot/.brew/Cellar/cmake/3.16.4/bin/cmake

# The command to remove a file.
RM = /Users/jpinyot/.brew/Cellar/cmake/3.16.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jpinyot/Desktop/GitHubRepositoris/42_ft_linear_regression

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jpinyot/Desktop/GitHubRepositoris/42_ft_linear_regression

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/jpinyot/.brew/Cellar/cmake/3.16.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/jpinyot/.brew/Cellar/cmake/3.16.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jpinyot/Desktop/GitHubRepositoris/42_ft_linear_regression/CMakeFiles /Users/jpinyot/Desktop/GitHubRepositoris/42_ft_linear_regression/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jpinyot/Desktop/GitHubRepositoris/42_ft_linear_regression/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft_linear_regression

# Build rule for target.
ft_linear_regression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ft_linear_regression
.PHONY : ft_linear_regression

# fast build rule for target.
ft_linear_regression/fast:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/build
.PHONY : ft_linear_regression/fast

srcs/estimatePrice.o: srcs/estimatePrice.cpp.o

.PHONY : srcs/estimatePrice.o

# target to build an object file
srcs/estimatePrice.cpp.o:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/srcs/estimatePrice.cpp.o
.PHONY : srcs/estimatePrice.cpp.o

srcs/estimatePrice.i: srcs/estimatePrice.cpp.i

.PHONY : srcs/estimatePrice.i

# target to preprocess a source file
srcs/estimatePrice.cpp.i:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/srcs/estimatePrice.cpp.i
.PHONY : srcs/estimatePrice.cpp.i

srcs/estimatePrice.s: srcs/estimatePrice.cpp.s

.PHONY : srcs/estimatePrice.s

# target to generate assembly for a file
srcs/estimatePrice.cpp.s:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/srcs/estimatePrice.cpp.s
.PHONY : srcs/estimatePrice.cpp.s

srcs/linearRegression.o: srcs/linearRegression.cpp.o

.PHONY : srcs/linearRegression.o

# target to build an object file
srcs/linearRegression.cpp.o:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/srcs/linearRegression.cpp.o
.PHONY : srcs/linearRegression.cpp.o

srcs/linearRegression.i: srcs/linearRegression.cpp.i

.PHONY : srcs/linearRegression.i

# target to preprocess a source file
srcs/linearRegression.cpp.i:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/srcs/linearRegression.cpp.i
.PHONY : srcs/linearRegression.cpp.i

srcs/linearRegression.s: srcs/linearRegression.cpp.s

.PHONY : srcs/linearRegression.s

# target to generate assembly for a file
srcs/linearRegression.cpp.s:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/srcs/linearRegression.cpp.s
.PHONY : srcs/linearRegression.cpp.s

srcs/mainLinReg.o: srcs/mainLinReg.cpp.o

.PHONY : srcs/mainLinReg.o

# target to build an object file
srcs/mainLinReg.cpp.o:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/srcs/mainLinReg.cpp.o
.PHONY : srcs/mainLinReg.cpp.o

srcs/mainLinReg.i: srcs/mainLinReg.cpp.i

.PHONY : srcs/mainLinReg.i

# target to preprocess a source file
srcs/mainLinReg.cpp.i:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/srcs/mainLinReg.cpp.i
.PHONY : srcs/mainLinReg.cpp.i

srcs/mainLinReg.s: srcs/mainLinReg.cpp.s

.PHONY : srcs/mainLinReg.s

# target to generate assembly for a file
srcs/mainLinReg.cpp.s:
	$(MAKE) -f CMakeFiles/ft_linear_regression.dir/build.make CMakeFiles/ft_linear_regression.dir/srcs/mainLinReg.cpp.s
.PHONY : srcs/mainLinReg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ft_linear_regression"
	@echo "... srcs/estimatePrice.o"
	@echo "... srcs/estimatePrice.i"
	@echo "... srcs/estimatePrice.s"
	@echo "... srcs/linearRegression.o"
	@echo "... srcs/linearRegression.i"
	@echo "... srcs/linearRegression.s"
	@echo "... srcs/mainLinReg.o"
	@echo "... srcs/mainLinReg.i"
	@echo "... srcs/mainLinReg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

